// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovcmxpjcvtjosivydhmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92Y214cGpjdnRqb3NpdnlkaG16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwODQwNTgsImV4cCI6MjA1MjY2MDA1OH0.lrgosBswhobQYxWw4vexjZelE8Dkgd1jRDugTzB_zG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);